name: ${name}
author: LightStudios
version: ${version}
main: io.lightstudios.core.LightCore
api-version: 1.20
depend: ["Vault"]
softdepend: ["Towny", "ProtocolLib", "PlaceholderAPI", "LightCoins", "WorldGuard", "MythicMobs", "Nexo"]
loadbefore: [ ]
libraries:
  # some servers do not include the libraries in the jar
  - org.mariadb.jdbc:mariadb-java-client:3.5.0
commands:
  lightcore:
    description: The root command for the api
    aliases: [core, lcore, lc]