name: lightCore
author: LightStudios
version: '0.2.8'
main: io.lightstudios.core.LightCore
api-version: 1.21
depend: ["Vault"]
softdepend: ["Towny", "ProtocolLib", "PlaceholderAPI"]
loadbefore: [ ]
libraries: [ ]
#  - org.mariadb.jdbc:mariadb-java-client:3.5.0
#  - com.zaxxer:HikariCP:6.0.0
commands:
  lightcore:
    description: The root command for the api
    aliases: [core, lcore, lc]